---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-volumeclaim
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
      - name: factorio
        image: gcr.io/fyb-k8s/factorio@sha256:476ab705d4d413acbc1b3d8c4daf85d116c18b8ee6497028a7996e114318606b
        ports:
        - containerPort: 34197
          protocol: UDP
        volumeMounts:
        - mountPath: /factorio/saves
          name: factorio-saves
        - mountPath: /factorio/mods
          name: factorio-mods
      volumes:
      - name: factorio-saves
        persistentVolumeClaim:
          claimName: factorio-volumeclaim
      - name: factorio-mods
        emptyDir: {}

---

kind: Service
apiVersion: v1
metadata:
  name: factorio
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: factorio
  ports:
  - port: 34197
    targetPort: 34197
    protocol: UDP
