---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-volumeclaim
  namespace: philde
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: philde
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
      - name: factorio
        image: gcr.io/flowing-digit-843/factorio@sha256:d4a20da2bfec16c6ead3316bd621427452ac17993b30bcd4378bef8701c326fd
        ports:
        - containerPort: 34197
          protocol: UDP
        volumeMounts:
        - mountPath: /factorio/saves
          name: factorio-saves
        - mountPath: /factorio/mods
          name: factorio-mods
      volumes:
      - name: factorio-saves
        persistentVolumeClaim:
          claimName: factorio-volumeclaim
      - name: factorio-mods
        emptyDir: {}

---

kind: Service
apiVersion: v1
metadata:
  name: factorio
  namespace: philde
spec:
  type: ClusterIP
  selector:
    app: factorio
  ports:
  - port: 34197
    targetPort: 34197
    protocol: UDP

---

apiVersion: "k8s.deslauriers.io/v1beta1"
kind: PortAddressTranslation
metadata:
  name: factorio-pat
  namespace: philde
spec:
  service: factorio
  port: 34197
